namePrefix: dev-

resources:
- deployment.yaml
- svc.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hellopy-demo
  newName: rosscdh/hellopy-demo
  newTag: 0.0.1

configMapGenerator:
- literals:
  - DEPLOY_VERSION='This is my test that is green'
  name: demo-cm
