apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

resources:
- deployment.yaml
- svc.yaml
- ingress.yaml

images:
- name: hellopy-demo
  newName: rosscdh/hellopy-demo
  newTag: 0.0.1

configMapGenerator:
- literals:
  - ENVIRONMENT_NAME='Mindcurv-Ed Talk'
  - DEPLOY_VERSION=red
  name: demo-cm
