apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc-active
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    nodePort: 31234
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-svc-preview
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    nodePort: 31235
    port: 8000
    targetPort: 8000