[tool.semantic_release]
patch_without_tag = true
major_on_zero = true
commit_parser = "semantic_release.history.emoji_parser"
upload_to_pypi = false
upload_to_release = false
version_variable = [
    "setup.py:__version__",
]
